// tempo-angular/src/app/beat-mark/beat-mark.component.ts
import { Component, OnInit } from '@angular/core';
import { TempoService } from '../tempo.service';
import { sleep } from 'src/lib/time';

@Component({
  selector: 'beat-mark',
  templateUrl: './beat-mark.component.html',
  styleUrls: ['./beat-mark.component.scss']
})
export class BeatMarkComponent  implements OnInit {
  beating:boolean = false;
  tempo:TempoService;

  constructor(tempo:TempoService) { this.tempo = tempo; }

  ngOnInit() {
    this.tick()
  }

  async tick() {
    if (this.tempo.isPlaying()) this.beating = !this.beating
    this.tempo.tick()
    await sleep(this.tempo.getBpms())
    this.tick()
  }

}

<div class="beat-mark-container" (click)="tempo.openSignatureSelection()">
  <figure [ngClass]="{ 'beating': beating }"></figure>
  <h1>{{ tempo.getTimeSignatureLabel() }}</h1>
</div>

// tempo-quasar/src/components/BeatMark.vue
<template lang="pug">
.beat-mark-container(@click="toggleTimeSignature")
  figure(:class="{ beating: beating }")
  h1="{{ tempoStore.timeSignatureLabel }}"
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useTempoStore } from 'src/stores/tempo'
import { sleep } from 'src/lib/time'

const tempoStore = useTempoStore()
const beating = ref(false)

const toggleTimeSignature = () =>
  tempoStore.showTimeSignatureSelector = !tempoStore.showTimeSignatureSelector

const tick = async () => {
  if (tempoStore.playing) beating.value = !beating.value
  tempoStore.tick()
  await sleep(tempoStore.bpms)
  tick()
}

onMounted(tick)
</script>
